name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
    - name: Run
      run: |
        cd api
        python run.py &

    - name: Wait for Flask server to start
      run: sleep 10s

    - name: Run test cases
      run : |
        pwd
        cd api/tests
        python test.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH client
      run: |
        sudo apt update
        sudo apt install openssh-client -y

    - name: Add known hosts
      run: |
        ssh-keyscan 103.240.91.206 >> ~/.ssh/known_hosts

    - name: Deploy to Local Machine
      run: |
        # Replace 'your_local_username' and 'your_local_ip' with your machine's details
        scp -r ./* root@103.240.91.206:/opt/
