name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        python run.py &

    - name: Wait for Flask server to start
      run: sleep 10s


    - name: Verify Flask server is running
      run: |
        $response = Invoke-WebRequest -Uri http://localhost:5000/omegaTron_test
        if ($response.StatusCode -eq 200) {
          Write-Output "Flask server is running"
        } else {
          Write-Error "Flask server is not running. Status code: $($response.StatusCode)"
          exit 1
        }

    - name: Run test cases
      run : |
        python test.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to Local Machine
      run: |
        # Replace 'your_local_username' and 'your_local_ip' with your machine's details
        scp -r ./* your_local_username@your_local_ip:/path/to/deployment/directory
